name: Docker Build and Push to AWS ECR

on:
  push:
    paths-ignore:
      - '.github/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGION: ${{ steps.login-ecr.outputs.region }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG